spring.application.name=MicroSave
spring.datasource.url=jdbc:mysql://localhost:3306/MicroSave
spring.datasource.username=root
spring.datasource.password=Deepi@123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
